on: push
name: Git Creation Demo
jobs:
  gitIssueCreation:
    name: Git Creation Demo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Git Creation Demo
        uses: bryan-nice/git-issue-creation@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_OWNER: 'bryan-nice'
          GITHUB_REPOSITORY: 'github-issue-creation'
          GITHUB_ISSUE_TITLE: 'Demo''ing Git Issue Creation'
          GITHUB_ISSUE_BODY: 'Demo''ing Git Issue Creation'